[package]
authors = ["Jorge Aparicio <jorge@japaric.io>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "A platform agnostic driver to interface the ENC28J60 (Ethernet controller)"
documentation = "https://docs.rs/enc28j60"
keywords = ["embedded-hal-driver", "Ethernet", "SPI"]
license = "MIT OR Apache-2.0"
name = "enc28j60"
readme = "README.md"
repository = "https://github.com/japaric/enc28j60"
version = "0.2.0"

[dependencies.cast]
version = "0.2.2"
default-features = false

[dependencies.embedded-hal]
version = "0.2.0"
features = ["unproven"]

[dependencies.byteorder]
default-features = false
version = "1.2.1"
